### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by steffi-graphdb** [steffi-graphdb/Steffi#3]
A Coninuous Integration server should be put in place in order to perform continuous testing and integration on STEFFI. A GitLab hook for is furthermore available which should allow the CI server to directly trigger builds on push.

Evaluate Travis and Jenkins.

**Comment by atsal** [comment]
STEFFI is using Travis-CI successfully now.

**Comment by sskhiri** [comment]
Where can we see the results ? What is the configuration ? Is the CI triggered every day on commit ? What if I have a develop branch can we have two 2 CI process one for dev and one for release on Master ? Can we have a build process that build an installation package ?

**Comment by atsal** [comment]
Build results can be traced at https://travis-ci.org/steffi-graphdb/Steffi

The configuration is set in the .travis.yml at the root folder of the project.

Travis CI will build after any git push to your GitHub project unless you instruct it to skip a build. In case we need a different behavior please let me know.

Yes, we can trigger a CI on multiple branches. Travis CI will always look for the .travis.yml file that is contained in the branch specified by the git commit that GitHub has passed to Travis CI. This configuration in one branch will not affect the build of another.

Yes, we can have a build process to do anything that we would be able to do via a maven script and not only since we can use actually any type of script. Strictly speaking we may define as an install command anything with the only limitation that has to exit with the 0 status in order to be considered successful.

**Comment by atsal** [comment]
One minor remark, currently I included only my email address in the notifications recipient list for testing purposes. Please let me know the individual email addresses or a distribution list to be included, and when they should be notified e.g. on success, on failure, always etc.
